import = ["/home/idko/.config/alacritty/themes/alacritty-theme/themes/onedark.toml"]

[font.normal]
family = "UbuntuMono Nerd Font"

[font]
size = 12

[window]
dynamic_padding = true
padding = { x = 8, y = 8 }

[selection]
save_to_clipboard = true

[keyboard]
bindings=[
	{key= "PageUp",  action= "ScrollHalfPageUp"},
	{key= "PageDown",  action= "ScrollHalfPageDown"}
]
